Avoid activating mpl v3.4 ax.is_first_col warning
I tried replacing by the recommended
  ax.get_subplotspec().is_first_col()
but got
  AttributeError: 'SubplotSpec' object has no attribute 'is_first_col'
in mpl v3.3.2