Fix ZQ-PA error in NumPy 2
SWd[k + 1] = X + Y
    ~~~^^^^^^^
ValueError: setting an array element with a sequence.

X and Y were 1-element arrays instead of scalars here
because SW and SWu/d0 were column arrays (M, 1)